---
- hosts: localhost
  tasks:

#
# whois `dig +short myip.opendns.com @resolver1.opendns.com` | grep country
# ansible-playbook -l localhost nagios.yml --extra-vars "timezone=`php -f timezone.php`"
#
# dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=5b408377-02 rootfstype=ext4 elevator=deadline fsck.repair=yes fsck.mode=force rootwait
#
# unicorn hat
# curl https://get.pimoroni.com/unicornhat | bash
#


   - name: Install utils
     become: true
     apt: name={{item}} state=installed
     with_items:
      - net-tools
      - nmap
      - nsca
      - nsca-client
      - ntpdate
      - openssl
      - parted
      - coreutils
      - davfs2
      - dnsutils
      - ethtool
      - fping
      - jwhois
      - python-passlib
      - rfkill
      - rsync
      - samba-common
      - samba-libs:armhf
      - socat
      - ssmtp
      - msmtp
      - unzip
      - usbutils
      - wget
      - whois
      - whiptail
      - wireless-tools
      - geoip-database
      - geoip-database-extra


## apache
   - name: Install apache
     become: true
     apt: name={{item}} state=installed
     with_items:
      - apache2
      - apache2-bin
      - apache2-data
      - apache2-utils
      - ca-certificates





##php
   - name: Install php
     become: true
     apt: name={{item}} state=installed
     with_items:
      - php-common
      - php-db
      - php-gettext
      - php-http
      - php-mbstring
      - php-net-ftp
      - php-pear
      - php-pecl-http
      - php-php-gettext
      - php-ssh2
      - php-xml
      - php7.0-cli
      - php7.0-common
      - php7.0-json
      - php7.0-mbstring
      - php7.0-mysql
      - php7.0-opcache
      - php7.0-readline
      - php7.0-xml
      - php-geoip
      - libapache2-mod-php7.0

   - name: restart apache
     service:
      name: apache2
      state: restarted
     become: true

   - name: Get timezone 
     shell: php -f timezone.php
     register: timezone

   - name: php.ini
     lineinfile:
      dest: /etc/php/7.0/apache2/php.ini
      state: present
      insertafter: ";date.timezone ="
      line: "date.timezone = {{ timezone.stdout }}"
     become: true

   - name: php.ini
     lineinfile:
      dest: /etc/php/7.0/cli/php.ini
      state: present
      insertafter: ";date.timezone ="
      line: "date.timezone = {{ timezone.stdout }}"
     become: true

   - name: restart apache
     service:
      name: apache2
      state: restarted
     become: true



### DB ###

   - name: Install MariaDB
     become: true
     apt: name={{item}} state=installed
     with_items:
      - mariadb-server-10.1
      - mariadb-client-10.1
      - mysql-utilities
      - python-mysql.connector
      - python-mysqldb
      - python3-mysql.connector
      - python3-mysqldb

   - name: Set MariaDB root password for the first time (root@localhost)
     become: true
     mysql_user:
       name: root
       password: "5pr1nG5pr1nG"
       host: localhost
       state: present
     tags: mariadb

   - name: Set MariaDB root password for 127.0.0.1, ::1
     become: true
     mysql_user:
       name: root
       password: "5pr1nG5pr1nG"
       host: "localhost"
       login_user: root
       login_password: "5pr1nG5pr1nG"
       state: present
     with_items:
       - ::1
       - 127.0.0.1
     tags: mariadb

   - name: Flush privileges
     become: true
     shell: mysql -u root -p5pr1nG5pr1nG -N -se "flush privileges"

   - name: Disable plugin uni_socket
     become: true
     shell: mysql -u root -5pr1nG5pr1nG -N -se "UPDATE mysql.user SET plugin = '' WHERE plugin = 'unix_socket';"

   - name: Restore database
     mysql_db:
      name: db_nagiosql_v32
      state: import
      target: nagiosql.sql
      target: v34.sql
      login_user: root
      login_password: 5pr1nG5pr1nG
     become: true

   - name: Add user
     mysql_user:
      name: nagiosql_32
      password: 'nagiosQL123'
      encrypted: no
      priv: 'db_nagiosql_v32.*:ALL'
      state: present
      login_user: root
      login_password: 5pr1nG5pr1nG
     become: true


###





### nagios ###

   - name: Install nagios
     become: true
     apt: name={{item}} state=installed
     with_items:
      - nagios-images
      - nagios-plugins
      - nagios-plugins-basic
      - nagios3
      - nagios3-cgi
      - nagios3-common
      - nagios3-core

### Tweaks for apache interface

   - name: delete index.html
     file:
      state: absent
      path: /var/www/html/index.html
     become: true

   - name: Create index.php redirection to Nagios
     shell: echo "<?php header('Location{{':'}} nagios3/'); exit; ?>" > /var/www/html/index.php
     become: true

   - name: add nagiosQL link
     lineinfile:
      dest: /usr/share/nagios3/htdocs/side.php
      state: present
      insertafter: '^<li><a href="main.php" target='
      line: '<li><a href="/nagiosql" target="_blank">NagiosQL</a></li>'
     become: true

   - name: change password nagios admin
     shell: htpasswd -b -c /etc/nagios3/htpasswd.users admin 'JwdJa'
     become: true

   - name: Creates directory
     become: true
     file:
       path: /var/www/html/nagiosql/
       state: directory
       owner: www-data
       group: www-data
       mode: 0775

   - name: Download nagiosQL
     unarchive:
      src: https://netix.dl.sourceforge.net/project/nagiosql/nagiosql/NagiosQL%203.4.0/nagiosql-3.4.0.tar.gz
      extra_opts: [--strip-components=1]
      dest: /var/www/html/nagiosql/
      remote_src: yes
     become: true



### ansible-playbook -l localhost nagios.yml --extra-vars "timezone=`php -f timezone.php`"



#   - shell: echo "I cat hello"
#     when: cat_contents.stdout == "hello"



   - name: "Create directory /var/lib/nagios/spool"
     become: true
     file:
      path: /var/lib/nagios/spool
      state: directory
      owner: nagios
      group: www-data
      mode: 0775

   - name: "Ceate directory /var/lib/nagios/spool/checkresults"
     become: true
     file:
      path: /var/lib/nagios/spool/checkresults
      state: directory
      owner: nagios
      group: www-data
      mode: 0775

   - name: "Ceate directory /var/lib/nagios3"
     become: true
     file:
      path: /var/lib/nagios3
      state: directory
      owner: nagios
      group: www-data
      mode: 0775

   - name: "Ceate directory /var/lib/nagios3/rw"
     become: true
     file:
      path: /var/lib/nagios3/rw
      state: directory
      owner: nagios
      group: www-data
      mode: 0775


### Final system tweaks
#pi@raspberrypi:~ $ echo Passw0rd | mkpasswd --method=sha-512 --password-fd=0
#$6$Wl5mFbmE476k/ep$bm6wCmlQdiqoBdwKh/z0nSMqHWi45UdAIZRpHZC4soNbzMzfYkvo2hacjk/4QmcDKq9.6qfBR7RlODGKtgjHe.

# done
#   - name: change password for user pi
#     user:
#      name=pi
#      update_password=always
#      password="$6$Wl5mFbmE476k/ep$bm6wCmlQdiqoBdwKh/z0nSMqHWi45UdAIZRpHZC4soNbzMzfYkvo2hacjk/4QmcDKq9.6qfBR7RlODGKtgjHe."
#     become: true
